sulu_utils.check_page_permissions:
    path: "/check/page/{id}.{_format}"
    methods: GET
    controller: "sulu_utils.auth_controller::checkPage"
    format: json
    requirements:
        _format: json
